### ISSUE TITLE
Lyrics Plus tab won't load

### ISSUE THREAD

**Issue by execOQ** [khanhas/spicetify-cli#1088]
## ℹ Computer information

- Spotify version: 
- 1.1.68.632.g2b11de83
- Spicetify version: 
- v2.6.4

## 📝 Provide detailed reproduction steps (if any)

1. spicetify config custom_apps lyrics-plus
2. spicetify apply

### ✔️ Expected result

The page with the text should be loaded

### ❌ Actual result

It spelled "Something went wrong"

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/44172382/134529361-ecf6b8cf-a01a-4c2b-bfc7-5790a3d0d5d0.png)

**Comment by itsmeow** [comment]
Fixed in 2.6.5

**Comment by execOQ** [comment]
Lyrics Plus is working, thanks

**Comment by execOQ** [comment]
I also wanted to ask, every time I want to see the text, I get such a smiley face, I decide this by going into Lyrics Plus Config and unchecking or putting a tick in front of Noise ovarlay. Is it possible to make the extension work without this action?

**Comment by afonsojramos** [comment]
Should be fixed in 2.6.6 @execOQ

**Comment by execOQ** [comment]
Unfortunately, version 2.6.6 did not fix anything, everything remained the same... @afonsojramos

**Comment by execOQ** [comment]
I just accidentally figured out how to solve the problem. The extension does not show the lyrics of the song that is playing right now, and for the lyrics to be shown, you need to put another track, but you cannot leave the Lyrics tab.


Here's a video: https://youtu.be/OLKhfOjk2qI

**Comment by afonsojramos** [comment]
Yeah, this is the same problem as #1090 then! Thank you @execOQ
