### ISSUE TITLE
Black screen after apply

### ISSUE THREAD

**Issue by NebulaBC** [khanhas/spicetify-cli#800]
## ℹ Computer information

- Spotify version: 1.1.61.583.gad060c66
- Spicetify version: 2.3.0

## 📝 Provide detailed reproduction steps (if any)

1. Download Spotify from spotify.com on Windows 10
2. Set Spicetify theme
3. Apply theme
4. Open, or re-open Spotify

### ✔️ Expected result

_Theme applied, and Spotify should look spicier!_

### ❌ Actual result

_Fully black window, and completely unresponsive to keystrokes_

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/49570924/123198995-10ee0680-d47c-11eb-81da-b07916da9808.png)
![image](https://user-images.githubusercontent.com/49570924/123199024-1ba89b80-d47c-11eb-9eb2-7451c3f27d78.png)

**Comment by khanhas** [comment]
1. Provide config file
2. Try `spicetify restore backup apply`

**Comment by neyako** [comment]
same problem

https://user-images.githubusercontent.com/64780385/123215128-42a1b480-d4f2-11eb-9943-2578d809d7fa.mp4

**Comment by khanhas** [comment]
@neyako provide Console error log would help me debug

**Comment by jason-wihardja** [comment]
I'm on macOS, and I faced a similar problem. Here's a screenshot of the DevTools on my machine

![image](https://user-images.githubusercontent.com/3488460/123289617-d1d2ba80-d53a-11eb-8dd4-09a9a65cafbd.png)

**Comment by NebulaBC** [comment]
I have tried restoring a backup, and it works, but each time I try to apply it just breaks again. My config should be default: https://p.neb.cx/efejoqopuh.ini

> 1. Provide config file
> 2. Try `spicetify restore backup apply`

**Comment by jason-wihardja** [comment]
Same here, everything is default on my side, apart from the custom theme I'm currently developing. But it's just CSS anyway. From my console, it seems like there's an error somewhere in the spicetify JS code

**Comment by neyako** [comment]
> @neyako provide Console error log would help me debug
image: 
![image](https://user-images.githubusercontent.com/64780385/123314665-0f444180-d555-11eb-957b-6efce29521fa.png)

video (i just mess everything, sr):
https://user-images.githubusercontent.com/64780385/123314639-06ec0680-d555-11eb-9de3-f5e45ad1b0e5.mp4

**Comment by NebulaBC** [comment]
> Same here, everything is default on my side, apart from the custom theme I'm currently developing. But it's just CSS anyway. From my console, it seems like there's an error somewhere in the spicetify JS code

I'm not even using a custom theme, I have tried multiple themes.

**Comment by khanhas** [comment]
@neyako Did you turn off "expose_api" in config file?
If you did, please turn it on and run `spicetify restore backup apply`.

**Comment by khanhas** [comment]
@jason-wihardja Have you tried running `spicetify restore backup apply`?

**Comment by khanhas** [comment]
Nvm, my Spotify just updated and I can confirm home_config prevents it from booting.

**Comment by jason-wihardja** [comment]
> @jason-wihardja Have you tried running `spicetify restore backup apply`?
> Also what is your Spotify version?

Yes, if I run `spicetify restore`, then everything is back normal. But as soon as I run `spicetify backup apply`, the same issue happens again. I'm on version 1.1.62.583.gdac868ed-a

**Comment by CharlieS1103** [comment]
Set home_config to 0 for now. @jason-wihardja

**Comment by 0Inspiration0** [comment]
i am having the same issue with the blackscreen again, i can't remeber what to do to fix it

**Comment by 0Inspiration0** [comment]
> i am having the same issue with the blackscreen again, i can't remeber what to do to fix it

sorry i just reinstalled spotify and its fine now

**Comment by CharlieS1103** [comment]
@jason-wihardja The issue is now fixed in the new version(or it should be) follow the upgrade steps and then try out the new home config!

**Comment by jason-wihardja** [comment]
Hi @CharlieS1103, I just upgraded and apparently the issue I mentioned at https://github.com/khanhas/spicetify-cli/issues/800#issuecomment-867728679 still occurs. Could it be a different issue altogether? Because my error message is different from what @neyako had mentioned at https://github.com/khanhas/spicetify-cli/issues/800#issuecomment-867866988

**Comment by khanhas** [comment]
@jason-wihardja Did you run `spicetify restore backup apply` after upgrading spicetify?
Anyway, try reinstall Spotify and run `spicetify backup apply`.
If problem still persists, can you take screenshot of Devtool in "Element" tab?

**Comment by jason-wihardja** [comment]
@khanhas Yes, I had run that command. Tried a fresh install, it still occurs. Here's the screenshot

![image](https://user-images.githubusercontent.com/3488460/123514348-d58e4a80-d6bc-11eb-8735-c895b2553823.png)

**Comment by jason-wihardja** [comment]
By the way I forgot to mention that since the last spicetify update @CharlieS1103 mentioned, the sidebar and playback footer appears, whereas in the previous version it's just blank. Here's how it currently looks like on my machine

![image](https://user-images.githubusercontent.com/3488460/123515071-5733a780-d6c0-11eb-8277-0543a8ae09be.png)

**Comment by khanhas** [comment]
@jason-wihardja  thank you. I found the bug. It will be fixed in next patch. At the moment, please add one extension to extensions list and it will not throw that error again. Any extension would do: https://github.com/khanhas/spicetify-cli/wiki/Extensions

**Comment by NebulaBC** [comment]
I have just updated to the most recent version of spicetify, but I am still having the same issue.

**Comment by vijaypanchalr3** [comment]
i have stilll this problem

**Comment by Legendmaster0000001** [comment]
i also have the problem that after keeping the theme the screen goes into the color theme that is set

**Comment by cyril-schroeder-ox** [comment]
I also get the same error still (Ubuntu 18.04).
After `spicetify apply` I get a black and unresponsive screen.
`spicetify restore` works though.

**Comment by ghabra69** [comment]
> 1. Provide config file
> 2. Try `spicetify restore backup apply`

works for me thanks

**Comment by Wrx95Pro** [comment]
Got the problem after Spicetify update to 2.25.2

**Comment by p70062790** [comment]
i'm still having this problem

**Comment by 1stator** [comment]
I'm still having this issue too. I've noticed it only after I have recently used my phone to listen to Spotify though and then changing to PC after. Not sure what the actual issue is though
